### ISSUE TITLE
gui locks up when changing material high speed

### ISSUE THREAD

**Issue by oilytin** [mstrens/Hot_wire#3]
If I load an existing project fil_chaud_2.ini and then try to alter the high speed in the materials tab the gui locks up and must be restarted.

**Comment by mstrens** [comment]
This is strange.
I can't reproduce the error.

Are you running the .exe program on a windows 64 bits system (or have you installed python and are running the script)?
Do you get an error message on the console?

**Comment by oilytin** [comment]
yea the exe, will check console now

**Comment by oilytin** [comment]
Nothing in the console, all i do is start the exe upload old project "fil_chaud_2.ini" select material tab and try to change the fast speed. as soon as i click away it locks up.
The low speed one seems to be unaffected.
![image](https://user-images.githubusercontent.com/64922090/84133996-cf8ce380-aa3f-11ea-939d-a4c45cdc2ec1.png)

**Comment by oilytin** [comment]
Hi mstrens,
after some more testing the only time it does it is when i load a project or profile and then change the fast speed to 5, any other number seems to work (trust me to pick the only one that doesn't!)
hope this helps.
if I change it and then load a profile i get the following error in the console.
`Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "fil_chaud_profil.py", line 79, in uploadRoot
  File "fil_chaud.py", line 691, in validateAll
  File "fil_chaud_cut.py", line 99, in calculateRedraw
  File "fil_chaud_cut.py", line 148, in calculate
  File "fil_chaud_cut.py", line 464, in calculate2Radiance
  File "fil_chaud_cut.py", line 483, in radiance
ZeroDivisionError: float division by zero`

**Comment by mstrens** [comment]
Thanks for the info.
I just tested it and I can reproduce the issue.

I will check the code to solve it.

**Comment by mstrens** [comment]
I just put a new version on github.
I think it fixed the issue (half speed was not updated when full speed was edited)

**Comment by oilytin** [comment]
Thanks, will have a look.
